# Generated by Django 3.0.4 on 2020-04-22 09:21

from django.db import migrations
import imagekit.models.fields
import production.models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_auto_20200422_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=production.models.Clients.upload_photo_dir),
        ),
    ]
