# Generated by Django 3.0.4 on 2020-04-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_clients_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='photo',
            new_name='image',
        ),
    ]
