# Generated by Django 3.0.4 on 2020-04-22 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_auto_20200422_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='image',
            new_name='imageSrc',
        ),
    ]
