# Generated by Django 3.0.4 on 2020-03-18 09:28

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('hrm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmploymentStatus',
            new_name='EmployementStatus',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employment_status',
            new_name='employement_status',
        ),
    ]
