# Generated by Django 3.0.4 on 2020-03-18 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_auto_20200318_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='full_name',
            new_name='fullName',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
