# Generated by Django 3.0.4 on 2020-03-18 11:48

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0003_auto_20200318_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
